version: '3.9'

volumes:
    deepstream:
        external: True

services:
    deepstream-app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                USER_UID=$(id -u)
                USER_GID=$(getent group docker | cut -d: -f3)
        # image: deepstream-app:latest

        user: root
        container_name: deepstream-app
        volumes: 
            - deepstream:/workspace

